<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fiap.Estrutura.Model\Fiap.Estrutura.Model.csproj" />
    <ProjectReference Include="..\Fiap.Estrutura.Repository\Fiap.Estrutura.Repository.csproj" />
  </ItemGroup>

</Project>
